*** Test Bench ***
Instructions fetched : 3 lines.
Memory used : 4 words.
Register 0 usage : %30.
Register 1 usage : %0.
Register 2 usage : %69.
Register 3 usage : %0.
Register 4 usage : %0.
Register 5 usage : %0.
Register 6 usage : %0.
Register 7 usage : %0.
Register 8 usage : %0.
Register 9 usage : %0.
Register 10 usage : %0.
Register 11 usage : %0.
Register 12 usage : %0.
Register 13 usage : %0.
Register 14 usage : %0.
Register 15 usage : %0.
